#!/usr/bin/env python3
"""Extract PALWORLD_TYPE_HINTS from PalworldSaveTools' paltypes.py and emit
the equivalent Rust const table.

Usage: gen-palworld-types.py <path to paltypes.py> > palworld_type_hints.rs

Parses the file with `ast` and pulls the dict literal out with
`ast.literal_eval` rather than importing the module, so this doesn't need
paltypes.py's sibling packages (palsav.archive, palsav.rawdata) on the path.
"""

import ast
import sys


def main() -> None:
    src = open(sys.argv[1]).read()
    tree = ast.parse(src)

    hints = None
    for node in tree.body:
        if (
            isinstance(node, ast.AnnAssign)
            and getattr(node.target, "id", None) == "PALWORLD_TYPE_HINTS"
        ):
            hints = ast.literal_eval(node.value)
            break
    if hints is None:
        raise SystemExit("PALWORLD_TYPE_HINTS not found in paltypes.py")

    print("// @generated by `make gen-palworld-types`. Do not edit by hand.")
    print("//")
    print("// Ported from PALWORLD_TYPE_HINTS in deafdudecomputers/PalworldSaveTools")
    print("// (https://github.com/deafdudecomputers/PalworldSaveTools, MIT).")
    print("// See src/palworld_types.rs for what consumes this table.")
    print()
    print("pub const PALWORLD_TYPE_HINTS: &[(&str, &str)] = &[")
    for path, hint in hints.items():
        path = path.lstrip(".")
        print(f'    ("{path}", "{hint}"),')
    print("];")


if __name__ == "__main__":
    main()
